services:
  mongo-competities:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_competitie:/data/db

  mysql-scheidsrechter:
    image: mysql:latest
    ports:
      - 3310:3306
    volumes:
      - mysqldb_scheidsrechter:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  mysql-wedstrijd:
    image: mysql:latest
    ports:
      - 3309:3306
    volumes:
      - mysqldb_wedstrijd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  competitie-service:
    depends_on:
      - mongo-competities
    image: brentpeeters/competitie
    ports:
      - 8080:8080
    links:
      - mongo-competities
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-competities

  scheidsrechter-service:
    depends_on:
      - mysql-scheidsrechter
    image: brentpeeters/scheidsrechter
    ports:
      - 8082:8082
    links:
      - mysql-scheidsrechter
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
      MYSQL_DB_HOST: mysql-scheidsrechter
      MYSQL_DB_PORT: 3310

  wedstrijd-service:
    depends_on:
      - mysql-wedstrijd
    image: brentpeeters/wedstrijd
    ports:
      - 8081:8081
    links:
      - mysql-wedstrijd
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
      MYSQL_DB_HOST: mysql-wedstrijd
      MYSQL_DB_PORT: 3309

  api-gateway:
    depends_on:
      - scheidsrechter-service
      - competitie-service
      - wedstrijd-service
    image: brentpeeters/api-gateway
    ports:
      - 8083:8083
    links:
      - scheidsrechter-service
      - competitie-service
      - wedstrijd-service
    environment:
      SCHEIDSRECHTER_SERVICE_BASEURL: scheidsrechter-service:8082
      COMPETITIE_SERVICE_BASEURL: competitie-service:8080
      WEDSTRIJD_SERVICE_BASEURL: wedstrijd-service:8081

volumes:
  mongodb_competitie:
  mysqldb_scheidsrechter:
  mysqldb_wedstrijd:
