server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: competitie-service
          uri: http://${COMPETITIE_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/competitie
            - Method=GET
          filters:
            - SetPath=/api/competitie

        - id: wedstrijd-service-all
          uri: http://${WEDSTRIJD_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/wedstrijd
            - Method=GET
          filters:
            - SetPath=/api/wedstrijd/all

        - id: scheidsrechter-service
          uri: http://${SCHEIDSRECHTER_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/scheidsrechter
          filters:
            - SetPath=/api/scheidsrechter