apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-competities
  name: mongo-competities
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-competities
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/enterprise-project-default: "true"
        io.kompose.service: mongo-competities
    spec:
      containers:
        - image: mongo:latest
          name: mongo-competities
          ports:
            - containerPort: 27017
              hostPort: 27017
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-competitie
      restartPolicy: Always
      volumes:
        - name: mongodb-competitie
          persistentVolumeClaim:
            claimName: mongodb-competitie
status: {}
