apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: scheidsrechter-service
  name: scheidsrechter-service
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
      nodePort: 30007
  selector:
    io.kompose.service: scheidsrechter-service
status:
  loadBalancer: {}
