apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: scheidsrechter-service
  name: scheidsrechter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheidsrechter-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/enterprise-project-default: "true"
        io.kompose.service: scheidsrechter-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB_HOST
              value: mysql-scheidsrechter
            - name: MYSQL_DB_PASSWORD
              value: root
            - name: MYSQL_DB_PORT
              value: "3310"
            - name: MYSQL_DB_USERNAME
              value: root
          image: brentpeeters/scheidsrechter
          name: scheidsrechter-service
          ports:
            - containerPort: 8082
              hostPort: 8082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
