apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: wedstrijd-service
  name: wedstrijd-service
spec:
  type: NodePort
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30008
  selector:
    io.kompose.service: wedstrijd-service
status:
  loadBalancer: {}
