apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: wedstrijd-service
  name: wedstrijd-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wedstrijd-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\peete\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/enterprise-project-default: "true"
        io.kompose.service: wedstrijd-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB_HOST
              value: mysql-wedstrijd
            - name: MYSQL_DB_PASSWORD
              value: root
            - name: MYSQL_DB_PORT
              value: "3309"
            - name: MYSQL_DB_USERNAME
              value: root
          image: brentpeeters/wedstrijd
          name: wedstrijd-service
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
